### ISSUE TITLE
Adding custom command to layout causes AttributeError: 'UUID' object has no attribute 'replace'

### ISSUE THREAD

**Issue by julius425** [gnome-terminator/terminator#273]
terminator 1.91
Ubuntu 20.04.1

Custom command brings up error or default terminator window with no layout(splits) saved, with local commands(launching apps etc.).
Launching with **-u** flag saves layout but doesnt execute command.

With network related commands(ssh tunneling for example) returns this traceback.

`Traceback (most recent call last):
  File "/usr/bin/terminator", line 86, in <module>
    dbus_service = ipc.DBusService()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 43, in __init__
    self.prepare_attributes()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 56, in prepare_attributes
    raise dbus.exceptions.DBusException(
dbus.exceptions.DBusException: Couldn't get DBus name net.tenshu.Terminator23558193cd9818af7fe4d2c2f5bd9d00f: Name exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 107, in <module>
    ipc.new_window_cmdline(optionslist)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 195, in _exec
    func(proxy, *args, **argd)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 201, in new_window_cmdline
    session.new_window_cmdline(options)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 72, in new_window_cmdline
    self.terminator.create_layout(oldopts.layout)
  File "/usr/share/terminator/terminatorlib/terminator.py", line 336, in create_layout
    window.create_layout(layout[windef])
  File "/usr/share/terminator/terminatorlib/window.py", line 889, in create_layout
    self.get_children()[0].create_layout(child)
  File "/usr/share/terminator/terminatorlib/terminal.py", line 1645, in create_layout
    self.uuid = make_uuid(layout['uuid'])
  File "/usr/share/terminator/terminatorlib/util.py", line 315, in make_uuid
    return uuid.UUID(str_uuid)
  File "/usr/lib/python3.8/uuid.py", line 166, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'UUID' object has no attribute 'replace'`

**Comment by mattrose** [comment]
This was fixed in a later release, try 

```
sudo add-apt-repository ppa:mattrose/terminator
sudo apt-get update
```

**Comment by julius425** [comment]
Thank you so much!
