### ISSUE TITLE
18.04 No module names 'configobj'

### ISSUE THREAD

**Issue by mckellyln** [gnome-terminator/terminator#31]
Hi,
I installed the latest terminator and ran -
```
sudo python3 ./setup.py install   --record=install-files.txt
```
then went to start it and -
```
% terminator
Traceback (most recent call last):
  File "/usr/local/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/local/lib/python3.6/dist-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/local/lib/python3.6/dist-packages/terminatorlib/config.py", line 75, in <module>
    from configobj import ConfigObj, flatten_errors
ModuleNotFoundError: No module named 'configobj'
```
Anyone have any ideas before I go digging ?
thx,
-m

**Comment by mckellyln** [comment]
I'm on Ubuntu 18.04 and latest termintor commit 53118b9eaa395c4f53ce64f6e5a3982c654d3417

**Comment by mckellyln** [comment]
ok, sorry my error not having configobj installed for python3.
