### ISSUE TITLE
Terminator crash on start

### ISSUE THREAD

**Issue by TheDalaiAlpaca** [gnome-terminator/terminator#34]
When I try to run terminator it crashes.  
```
$ terminator
Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3.8/site-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3.8/site-packages/terminatorlib/config.py", line 75, in <module>
    from configobj import ConfigObj, flatten_errors
ModuleNotFoundError: No module named 'configobj'
$ pacman -Q terminator
terminator 1.92-1
$ uname -r
5.6.5-arch3-1
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	n/a
```

Terminator used to work on my system, but not anymore after a reboot. 
Reinstalling the package had no effect.

**Comment by mckellyln** [comment]
Hi,
Install python3-configobj dependency.
The list of all of them is in the INSTALL file:
```
 * Python 3.5+ recommended:

     Debian/Ubuntu: python3
     Fedora/CentOS: python3
     FreeBSD: python37

 * Python GTK and VTE bindings:
     
     Fedora/CentOS: python3-gobject python3-configobj python3-psutil vte291 
		    keybinder3 intltool gettext
     Debian/Ubuntu: python3-gi python3-psutil python3-configobj 
		    gir1.2-keybinder-3.0 gettext intltool
     FreeBSD:       py37-psutil py37-configobj keybinder-gtk3 py37-gobject3 gettext 
		    intltool
```

**Comment by lazyfrosch** [comment]
Please check existing and closed issues before creating a new one. Dependencies are usually handled by the distribution packages, so here is the bug to go for: https://bugs.archlinux.org/task/66332?project=5&string=terminator

see #32 #31

**Comment by lazyfrosch** [comment]
Please check existing and closed issues before creating a new one. Dependencies are usually handled by the distribution packages, so here is the bug to go for: https://bugs.archlinux.org/task/66332?project=5&string=terminator

see #32 #31
