### ISSUE TITLE
Using the `--debug-classes` option makes terminator crash

### ISSUE THREAD

**Issue by nojhan** [gnome-terminator/terminator#397]
For instance:
`python3 terminator -g /dev/null --debug-classes=URLHandler`

Outputs:
```
Traceback (most recent call last):
  File "terminator", line 70, in <module>
    OPTIONS,dbus_options = terminatorlib.optionparse.parse_options()
  File "/home/nojhan/code/terminator/terminatorlib/optionparse.py", line 123, in parse_options
    if not options.debug > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

On Ubuntu 20.04 11.1, with terminator at 3a639266

**Comment by mattrose** [comment]
oh.  Let me see if I can reproduce this one

**Comment by mattrose** [comment]
Oh, you need the -d flag before you can call --debug-classes or --debug-methods

try
```
python3 terminator -g /dev/null -d --debug-classes=URLHandler
```

**Comment by nojhan** [comment]
How can I update the doc to indicate that?
-- 
nojhan
