### ISSUE TITLE
ImportError: bad magic number in 'six': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by yurinek** [gnome-terminator/terminator#404]
hi,

when opening terminator I get

`Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3/dist-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3/dist-packages/terminatorlib/config.py", line 75, in <module>
    from configobj import ConfigObj, flatten_errors
  File "/usr/lib/python3/dist-packages/configobj.py", line 22, in <module>
    import six
ImportError: bad magic number in 'six': b'\x03\xf3\r\n'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ImportError: bad magic number in 'six': b'\x03\xf3\r\n'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3/dist-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3/dist-packages/terminatorlib/config.py", line 75, in <module>
    from configobj import ConfigObj, flatten_errors
  File "/usr/lib/python3/dist-packages/configobj.py", line 22, in <module>
    import six
ImportError: bad magic number in 'six': b'\x03\xf3\r\n'
`

os: linux mint 20  Ulyana
terminator: 2.0.1-1-0ubuntu3

how should I resolve this?

**Comment by mattrose** [comment]
This does not appear to be a problem in terminator, but in the python 'six' package or your python configuration.
