### ISSUE TITLE
terminator failing to open on ubuntu 21.04

### ISSUE THREAD

**Issue by rjl9** [gnome-terminator/terminator#502]
This morning, terminator no longer opens. Instead i get the following error -->

Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3/dist-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3/dist-packages/terminatorlib/config.py", line 76, in <module>
    from configobj import ConfigObj, flatten_errors
  File "/usr/lib/python3/dist-packages/configobj.py", line 22, in <module>
    import six
ImportError: bad magic number in 'six': b'\x03\xf3\r\n'

**Comment by mattrose** [comment]
Ths would be a problem with your python installation.  See here for some details: https://community.letsencrypt.org/t/python-error-after-upgrade-from-deb8-to-deb9/61131/11

the tl;dr is that there's likely a compiled version of six from python2.7 somewhere in your path
