### ISSUE TITLE
Error when using "Insert Terminal Number" (Solved?)

### ISSUE THREAD

**Issue by VictorHomsi** [gnome-terminator/terminator#517]
Hello,

I recently installed terminator on my Linux Mint with Gnome desktop, and the button to Insert Terminal Number was not working.

Looking into the logs, I found the following error:

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 592, in do_enumerate
    term.feed(numstr % (idx + 1))
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 1584, in feed
    self.vte.feed_child(text)
TypeError: Item 0: Must be number, not str
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_terminator.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 592, in do_enumerate
    term.feed(numstr % (idx + 1))
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 1584, in feed
    self.vte.feed_child(text)
TypeError: Item 0: Must be number, not str`

I didn't found any solution on the internet, so I've tried to do some changes based on this error "TypeError: Item 0: Must be number, not str`" and the following one solved the problem:

Change line 1584 of /usr/lib/python3/dist-packages/terminatorlib/terminal.py
From: 
`self.vte.feed_child(text)`
To:
`self.vte.feed_child(bytes(text, 'utf-8'))`

I don't know if it works for all distributions, but worked here and worked on my friend Ubuntu installation.

More information about my installation:

```
$ cat /etc/linuxmint/info
RELEASE=20.1
CODENAME=ulyssa
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20.1 Ulyssa"
DESKTOP=Gnome
TOOLKIT=GTK
```

**Comment by yurenchen000** [comment]
> Yeah, I think I fixed this in a recent commit that hasn't made it to master yet.
> 
> Yep, found the same thing when I was working on an unrelated feature. [b80d133#diff-6ce5ab066e8371d795b8827ba0e6d341c3adad798380e047cd216e6893eb7d0c](https://github.com/gnome-terminator/terminator/commit/b80d133ccf1f126c259ea73a3ed87020e40dc0b1#diff-6ce5ab066e8371d795b8827ba0e6d341c3adad798380e047cd216e6893eb7d0c)


also meet this error, 
this diff works (metioned in mattrose commit)

```diff
--- /tmp//terminator.py	2021-04-03 04:11:15.000000000 +0800
+++ /usr/lib/python3/dist-packages/terminatorlib/terminator.py	2022-04-10 06:08:46.084446414 +0800
@@ -589,7 +589,7 @@
 
         for term in self.get_target_terms(widget):
             idx = terminals.index(term)
-            term.feed(numstr % (idx + 1))
+            term.feed(numstr.encode() % (idx + 1))
 
     def get_sibling_terms(self, widget):
         termset = []

```
