### ISSUE TITLE
Cannot launch terminator on archlinux

### ISSUE THREAD

**Issue by Breigner01** [gnome-terminator/terminator#528]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**
Terminator is not launching anymore (I still have one terminal open for now) and when I try to launch it in command line, it spits the following error: `You need to install the python bindings for gobject, gtk and pango to run Terminator.`
It happened right after updating my packages (which I do everyday).

**To Reproduce**
Try to launch Terminator on Archlinux with every packet up to date.

**Expected behavior**
Terminator should start

**Screenshots**

**Desktop (please complete the following information):**
 - OS Archlinux
 - Version 5.14.9-arch2-1
 - Terminator Version 2.1.1-2

**Additional context**
The output of pip freeze (python version 3.9.7):
```
appdirs==1.4.4
asn1crypto==1.4.0
attrs==21.2.0
Automat==20.2.0
bcrypt==3.2.0
Beaker==1.11.0
bottle==0.12.19
breezy==3.2.0
Brlapi==0.8.3
btrfsutil==5.14.2
CacheControl==0.12.6
cached-property==1.5.2
ceph==1.0.0
ceph-volume==1.0.0
cephfs==2.0.0
cephfs-shell==0.0.1
certifi==2021.10.8
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.7
click==8.0.3
cmd2==2.2.0
colorama==0.4.4
colour==0.1.5
conan==1.40.3
configobj==5.1.0.dev0
constantly==15.1.0
contextlib2==0.6.0.post1
cram==0.7
cryptography==35.0.0
Cython==0.29.24
daemonize==2.5.0
dbus-python==1.2.18
decorator==5.1.0
defusedxml==0.7.1
distlib==0.3.3
distro==1.6.0
dnspython==2.1.0
docker==5.0.3
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
dulwich==0.20.25
fasteners==0.16
flit_core==3.4.0
future==0.18.2
gcovr==5.0
Glances==3.2.2
greenlet==1.1.2
html5lib==1.1
hyperlink==21.0.0
idna==3.2
importlib-metadata==4.8.1
incremental==21.3.0
iniconfig==1.1.1
Jinja2==3.0.2
jsonschema==3.2.0
lensfun==0.3.95
libfdt==1.6.1
libmsym==0.2.4
libvirt-python==7.8.0
lit==12.0.1.dev0
louis==3.19.0
lxml==4.6.3
Mako==1.1.5
Markdown==3.3.4
MarkupSafe==2.0.1
meson==0.59.2
more-itertools==8.10.0
msgpack==1.0.2
netsnmp-python==1.0a1
node-semver==0.8.0
notify2==0.3.1
numpy==1.21.2
openrazer==3.1.0
openrazer-daemon==3.1.0
ordered-set==4.0.2
packaging==20.9
paramiko==2.7.2
patch-ng==1.17.4
patiencediff==0.2.2
pep517==0.11.0
pluggy==0.13.1
pluginbase==1.0.0
ply==3.11
progress==1.6
psutil==5.8.0
pwquality==1.4.4
py==1.10.0
pybind11==2.8.0
pycairo==1.20.1
pycparser==2.20
Pygments==2.10.0
PyGObject==3.40.1
PyHamcrest==1.10.1
PyJWT==2.2.0
PyNaCl==1.4.0
pynvim==0.4.3
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyperclip==1.8.2
PyQt5==5.15.5
PyQt5-sip==12.9.0
PyQtWebEngine==5.15.5
pyrsistent==0.18.0
pyte==0.8.0
pytest==6.2.2
python-dateutil==2.8.2
python-dotenv==0.19.1
pyudev==0.22.0.dev20201112
PyYAML==5.4.1
QtPy==1.11.2
rados==2.0.0
rbd==2.0.0
requests==2.26.0
resolvelib==0.5.5
retrying==1.3.3
rgw==2.0.0
setproctitle==1.2.2
six==1.16.0
team==1.0
terminator==2.1.1
texttable==1.6.4
thefuck==3.31
toml==0.10.2
tomli==1.2.1
tqdm==4.62.3
Twisted==21.7.0
typing-extensions==3.10.0.2
urllib3==1.26.7
validate==5.1.0.dev0
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.59.0
zipp==3.6.0
zope.interface==5.4.0
```

**Comment by Breigner01** [comment]
Well it throws an error when importing gi:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/breigner01/.local/lib/python3.9/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```
So I'm gonna look to install this lib but it should already be installed since it's necessary

**Comment by Breigner01** [comment]
Ok well the real problem is that I have libffi.so.8 installed and it looks for libffi.so.7 so yeah.

**Comment by mattrose** [comment]
Closing, It's not terminator code.

**Comment by derenv** [comment]
For those who need to find libffi.so.7, [install it](http://aur.archlinux.org/packages/libffi7) from the aur i.e. from your package manager GUI or:
`sudo yay -S libffi7`

**Comment by Breigner01** [comment]
I basically did that but it shouldn't be necessary.
And you shouldn't sudo yay and you aren't certain that every arch user or arch based distros have yay installed (some don't even know it exists and other package manager for aur exist).

**Comment by mattrose** [comment]
Talk to the Arch package maintainer.  There's no reason why the gir code can't link against the latest version of libffi.

**Comment by derenv** [comment]
yeah that's probably worth doing @mattrose, i think it's just a case of the package not being updated for it yet.

@Breigner01 hence the 'or' - that is true though (i forgot about not sudoing it tbh, i tend to just use the GUI for aur packages).

**Comment by Breigner01** [comment]
I'll look for arch package maintainer but last time I checked the package was flagged out of date since beginning of september.

Well what I meant by assuming someone knows yay and basically aur in general, is not a good idea because you have to install yay or any other aur package manager, hence not everyone has access to aur (even if imo arch isn't complete without aur).

For the sudo yeah I basically do everything in cli so I kinda know about that and if you sudo yay will warn you not to.

**Comment by derenv** [comment]
yup its not been updated since april :( i've added a bug report (i think that's right? should it be flagged as out-of-date instead for a bad dependency?)

fair enough! i switched to manjaro recently after like 4 years of ubuntu, still getting to grips with arch-esque stuff like aur tbh

Yeah i've had the warning hahaha i just forgot

**Comment by Breigner01** [comment]
Well I don't know if it should be flagged out of date or not. But when I saw it flagged out of date I went to submit a bug but it is written in the rules to submit a bug to not submit one if the package is flagged out of date.

**Comment by derenv** [comment]
Then we probably need to contact the maintainer, i'm not quite sure how to do that from the package page though.

**Comment by mattrose** [comment]
I think @grazzolini is one of the arch maintainers, though arch has a few different packages so I'm not sure what exactly he's responsible for, but he might be able to point people here in the right direction

**Comment by Scimmia22** [comment]
> Talk to the Arch package maintainer. There's no reason why the gir code can't link against the latest version of libffi.

Arch's gir code *does* link against the latest version of libffi. They aren't using Arch's package, though, they're loading things from their home dir. Not an Arch issue in any way.
