### ISSUE TITLE
dbus FileNotFoundError

### ISSUE THREAD

**Issue by 5l1v3r1** [gnome-terminator/terminator#58]
```
Traceback (most recent call last):
  File "/usr/local/bin/terminator", line 87, in <module>
    dbus_service = ipc.DBusService()
  File "/usr/local/lib/python3.7/dist-packages/terminatorlib/ipc.py", line 42, in __init__
    self.prepare_attributes()
  File "/usr/local/lib/python3.7/dist-packages/terminatorlib/ipc.py", line 56, in prepare_attributes
    "Couldn't get DBus name %s: Name exists" % BUS_NAME)
dbus.exceptions.DBusException: Couldn't get DBus name net.tenshu.Terminator21a9d5db22c73a993ff0b42f64b396873: Name exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/terminator", line 108, in <module>
    ipc.new_window_cmdline(optionslist)
  File "/usr/local/lib/python3.7/dist-packages/terminatorlib/ipc.py", line 194, in _exec
    func(proxy, *args, **argd)
  File "/usr/local/lib/python3.7/dist-packages/terminatorlib/ipc.py", line 200, in new_window_cmdline
    session.new_window_cmdline(options)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/terminatorlib/ipc.py", line 71, in new_window_cmdline
    self.terminator.create_layout(oldopts.layout)
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 310, in create_layout
    window, terminal = self.new_window()
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 233, in new_window
    terminal = maker.make('Terminal')
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 93, in make
    output = func(**kwargs)
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 105, in make_terminal
    return(terminal.Terminal())
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 141, in __init__
    self.cwd = get_default_cwd()
  File "/usr/lib/python3/dist-packages/terminatorlib/cwd.py", line 28, in get_default_cwd
    cwd = os.getcwd()
FileNotFoundError: 
```

**Comment by lazyfrosch** [comment]
This could happen when there is some quirk with dbus.

Can you describe your system and desktop environment?

**Comment by 5l1v3r1** [comment]
kali 2020 with linux kernel 5.2. it might be a dbus problem but i still dont understand why sometimes it works , sometimes not. i reverted back to python2 version but same problem occured after. Most probably the script cannot locate the folder and thinks it is deleted. You might make some addition to a temp folder with except rule.

**Comment by lazyfrosch** [comment]
dbus implementation can be quirky, I've seen another bug where it failed when no dbus was available.

**Comment by lazyfrosch** [comment]
Related: https://bugs.launchpad.net/terminator/+bug/1874722

**Comment by mattrose** [comment]
I think this may happen when you start terminator from a directory, and then remove the directory, and then try and start a new terminator window.  Just from reading the traceback.  I'll see if I can reproduce this.

**Comment by mattrose** [comment]
Yep.  found a reliable way to reproduce it:

first, ensure no other terminator instances are running, then do the following
```
mkdir /tmp/foo
cd /tmp/foo
terminator
```
Then, in the new terminator window that appears:
```
cd /tmp
rm -rf foo
terminator
```

et voila!  Traceback.

Maybe if os.getcwd() in the new window code fails, set a path of $HOME. Honestly, it's either that, or ... 
just don't cause the conditions that trigger this traceback
