### ISSUE TITLE
Unable to launch KeyError: b'Rss:'

### ISSUE THREAD

**Issue by dennis97519** [gnome-terminator/terminator#601]
**Describe the bug**
```
layout creation failed, creating a window ("b'Rss:'")
Traceback (most recent call last):
  File "/usr/bin/terminator", line 129, in <module>
    TERMINATOR.create_layout(OPTIONS.layout)
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 285, in create_layout
    window, terminal = self.new_window()
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 208, in new_window
    terminal = maker.make('Terminal')
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 93, in make
    output = func(**kwargs)
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 105, in make_terminal
    return(terminal.Terminal())
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 135, in __init__
    self.cwd = get_pid_cwd()
  File "/usr/lib/python3/dist-packages/terminatorlib/cwd.py", line 17, in get_pid_cwd
    psinfo =  psutil.Process(pid).as_dict()
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 630, in as_dict
    ret = meth()
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1215, in memory_maps
    it = self._proc.memory_maps()
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1834, in memory_maps
    data[b'Rss:'],
KeyError: b'Rss:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 132, in <module>
    TERMINATOR.new_window()
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 208, in new_window
    terminal = maker.make('Terminal')
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 93, in make
    output = func(**kwargs)
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 105, in make_terminal
    return(terminal.Terminal())
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 135, in __init__
    self.cwd = get_pid_cwd()
  File "/usr/lib/python3/dist-packages/terminatorlib/cwd.py", line 17, in get_pid_cwd
    psinfo =  psutil.Process(pid).as_dict()
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 630, in as_dict
    ret = meth()
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1215, in memory_maps
    it = self._proc.memory_maps()
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1834, in memory_maps
    data[b'Rss:'],
KeyError: b'Rss:'
```

**To Reproduce**
Fresh installation of Ubuntu on WSL 2
DISPLAY and windows firewall configured to connect to Xming
```
sudo add-apt-repository ppa:mattrose/terminator
sudo apt update
sudo apt install -y terminator
terminator
```

**Expected behavior**
Terminator launches

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Ubuntu on WSL2
 - Version 20.04.4 LTS
 - Display Technology: probably X11
Python 3 version 3.8.10
Terminator version 2.1.1

**Comment by dennis97519** [comment]
Somehow manually setting the wsl version for the distribution to 2 (`wsl --ser-version Ubuntu 2`) fixed this, closing
