### ISSUE TITLE
terminator runs in network namespace only with -u option (dbus)

### ISSUE THREAD

**Issue by lazyfrosch** [gnome-terminator/terminator#65]
Copied from Launchpad: https://bugs.launchpad.net/terminator/+bug/1874722

Terminator cannot be started inside a network namespace.

Running terminator 1.91 on Debian 10 (buster), Kernel 4.19.0-8-amd64 x86_64, Xfce 4.12.4

I generally setup the new network namespace (call it nns1), then I issue:

```
$ sudo ip netns exec nns1 su -c "terminator -d -d " mario

(terminator:16069): dbind-WARNING **: 14:40:12.594: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-HMTnanv0jP: Connection refused
ConfigBase::__init__: Borg::__init__: Preparing borg state for ConfigBase (/usr/share/terminator/terminatorlib/borg.py:47)
noclass::get_config_dir: Found config dir: /home/mario/.config (/usr/share/terminator/terminatorlib/util.py:194)
ConfigBase::load: looking for config file: /home/mario/.config/terminator/config (/usr/share/terminator/terminatorlib/config.py:604)
ConfigBase::load: config validated successfully (/usr/share/terminator/terminatorlib/config.py:632)
ConfigBase::load: ConfigBase::load: Processing section: global_config (/usr/share/terminator/terminatorlib/config.py:635)
ConfigBase::load: ConfigBase::load: Processing section: keybindings (/usr/share/terminator/terminatorlib/config.py:635)
ConfigBase::load: ConfigBase::load: Processing keybindings: zoom_in (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: zoom_out (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: zoom_normal (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: new_tab (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: cycle_next (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: cycle_prev (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: go_next (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: go_prev (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: go_up (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: go_down (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: go_left (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: go_right (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: rotate_cw (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: rotate_ccw (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: split_horiz (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: split_vert (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: close_term (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: copy (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: paste (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: toggle_scrollbar (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: search (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: close_window (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: resize_up (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: resize_down (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: resize_left (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: resize_right (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: move_tab_right (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: move_tab_left (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: toggle_zoom (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: scaled_zoom (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: next_tab (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: prev_tab (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: full_screen (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: reset (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: reset_clear (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: hide_window (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: group_all (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: ungroup_all (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: group_tab (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: ungroup_tab (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: new_window (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: new_terminator (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: broadcast_off (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: broadcast_group (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: broadcast_all (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: insert_number (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: insert_padded (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: edit_window_title (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: edit_tab_title (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: edit_terminal_title (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: layout_launcher (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing keybindings: help (/usr/share/terminator/terminatorlib/config.py:664)
ConfigBase::load: ConfigBase::load: Processing section: profiles (/usr/share/terminator/terminatorlib/config.py:635)
ConfigBase::load: ConfigBase::load: Processing profile: default (/usr/share/terminator/terminatorlib/config.py:639)
ConfigBase::load: ConfigBase::load: Processing section: layouts (/usr/share/terminator/terminatorlib/config.py:635)
ConfigBase::load: ConfigBase::load: Processing layouts: default (/usr/share/terminator/terminatorlib/config.py:654)
ConfigBase::load: ConfigBase::load: Processing section: plugins (/usr/share/terminator/terminatorlib/config.py:635)
Config::set_profile: Config::set_profile: Changing profile to default (/usr/share/terminator/terminatorlib/config.py:299)
Config::connect_gsetting_callbacks: GSetting connects for system changes (/usr/share/terminator/terminatorlib/config.py:360)
noclass::parse_options: OptionParse::parse_options: command line options: {'version': None, 'maximise': None, 'fullscreen': None, 'borderless': None, 'hidden': None, 'forcedtitle': None, 'geometry': None, 'command': None, 'config': '/home/mario/.config/terminator/config', 'execute': None, 'working_directory': None, 'classname': None, 'forcedicon': None, 'role': None, 'layout': 'default', 'select': None, 'profile': None, 'nodbus': None, 'debug': 2, 'debug_classes': None, 'debug_methods': None, 'new_tab': None, 'dummy': None} (/usr/share/terminator/terminatorlib/optionparse.py:154)
ConfigBase::load: ConfigBase::load: config already loaded (/usr/share/terminator/terminatorlib/config.py:594)
Config::set_profile: Config::set_profile: Changing profile to default (/usr/share/terminator/terminatorlib/config.py:299)
Config::connect_gsetting_callbacks: GSetting connects for system changes (/usr/share/terminator/terminatorlib/config.py:360)
ConfigBase::get_item: ConfigBase::get_item: dbus found in globals: True (/usr/share/terminator/terminatorlib/config.py:726)
function::with_proxy: dbus client call: new_window_cmdline (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: new_tab_cmdline (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: new_window (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: new_tab (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: hsplit (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: vsplit (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: get_terminals (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: get_window (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: get_window_title (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: get_tab (/usr/share/terminator/terminatorlib/ipc.py:191)
function::with_proxy: dbus client call: get_tab_title (/usr/share/terminator/terminatorlib/ipc.py:191)
DBusService::__init__: Borg::__init__: Preparing borg state for DBusService (/usr/share/terminator/terminatorlib/borg.py:47)
DBusService::prepare_attributes: Checking for bus name availability: net.tenshu.Terminator21a9d5db22c73a993ff0b42f64b396873 (/usr/share/terminator/terminatorlib/ipc.py:49)
noclass::<module>: Unable to become master process, operating via DBus (/usr/bin/terminator:88)
noclass::<module>: Requesting a new window (/usr/bin/terminator:106)
Traceback (most recent call last):
  File "/usr/bin/terminator", line 86, in <module>
    dbus_service = ipc.DBusService()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 43, in __init__
    self.prepare_attributes()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 50, in prepare_attributes
    bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-pgBBhfJzT4: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 107, in <module>
    ipc.new_window_cmdline(optionslist)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 193, in _exec
    bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-pgBBhfJzT4: Connection refused
```

terminator can however be run with the -u option:

```
$ sudo ip netns exec downl su -c "terminator -u" mario

(terminator:16334): dbind-WARNING **: 14:47:26.278: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-HMTnanv0jP: Connection refused

** (terminator:16334): WARNING **: 14:47:26.371: Binding '<Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.

I have a trivial configuration file:

$ cat .config/terminator/config
[global_config]
[keybindings]
[profiles]
  [[default]]
    background_color = "#ffffff"
    cursor_color = "#aaaaaa"
    foreground_color = "#000000"
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
```

**Comment by mattrose** [comment]
I think we can trap any exceptions from the DbusService() call and treat them as regular errors, rather than crashing out.

**Comment by mattrose** [comment]
Interesting, I tried to reproduce this on Fedora, but couldn't.  @lazyfrosch do you have a debian 10 env handy that you can test this with?

**Comment by mattrose** [comment]
Also tried on debian 10 (I found a VM lying around on my laptop) and the same command also worked there.

There might be improvements in the newer kernel or ip netns stack that have fixed this.  I say we close this bug.

**Comment by mattrose** [comment]
I'm gonna close this.  I'm pretty sure that this is fixed now with PR #88

**Comment by mattrose** [comment]
whoops, haven't actually merged that yet.

**Comment by mattrose** [comment]
merged now
