### ISSUE TITLE
Terminator not working with latest version of python-cairo

### ISSUE THREAD

**Issue by Breigner01** [gnome-terminator/terminator#711]
**Describe the bug**
Terminator fails to start with the latest version of python-cairo available on archlinux which is 1.23.0-3.

Here are the error logs:
```
Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3.10/site-packages/terminatorlib/optionparse.py", line 22, in <module>
    from terminatorlib.terminator import Terminator
  File "/usr/lib/python3.10/site-packages/terminatorlib/terminator.py", line 12, in <module>
    from . import borg
  File "/usr/lib/python3.10/site-packages/terminatorlib/borg.py", line 11, in <module>
    from .util import dbg
  File "/usr/lib/python3.10/site-packages/terminatorlib/util.py", line 21, in <module>
    import cairo
  File "/home/breigner01/.local/lib/python3.10/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/breigner01/.local/lib/python3.10/site-packages/cairo/_cairo.cpython-310-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
```

And here's my config:
```
[global_config]
[keybindings]
  help = None
[profiles]
  [[default]]
    icon_bell = False
    background_darkness = 0.85
    background_type = transparent
    cursor_shape = ibeam
    font = JetBrainsMono Nerd Font 10
    scrollback_lines = 1000
    scrollback_infinite = True
    palette = "#000000:#cd0000:#00cd00:#cdcd00:#0000ee:#cd00cd:#00cdcd:#e5e5e5:#7f7f7f:#ff0000:#00ff00:#ffff00:#5c5cff:#ff00ff:#00ffff:#ffffff"
    use_system_font = False
    use_theme_colors = True
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
```

**To Reproduce**
- On an up to date archlinux system
- Start terminator

**Expected behavior**
Terminator starts normally

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Archlinux
 - Version: 5.15.91-1-lts
 - Display Technology: X11 (KDE)

**Comment by mattrose** [comment]
This looks like Arch didn't package cairo correctly, or is missing the gobject-introspection binaries for python.  Or, you're using a custom python which doesn't link against the newly installed version of cairo, based on:
`ImportError: /home/breigner01/.local/lib/python3.10/site-packages/cairo/_cairo.cpython-310-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index`
