### ISSUE TITLE
Tiling commands broken

### ISSUE THREAD

**Issue by TheAalCh3m1st** [gnome-terminator/terminator#953]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**
Tiling broke after an OS update
**To Reproduce**
R click split terminal
**Expected behavior**
Split terminal horizontally or vertically

**Screenshots**
![Screenshot from 2024-09-28 15-17-43](https://github.com/user-attachments/assets/63660c70-0178-4079-be65-a3cbe95313ba)
**Desktop (please complete the following information):**
 - OS or Linux Distribution: [Debian]
 - Version [6.10.9]
 - Display Technology: Wayland or X11 [GDM3]

**Additional context**

Shift+Ctrl+A or Shift+Ctrl+O will not split terminal

**Comment by mattrose** [comment]
Weird, I will try to reproduce this.  It looks like GLib changed the way it's parsing URIs.

**Comment by TheAalCh3m1st** [comment]
Thanks

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by shurdanil** [comment]
I have the same problem on fedora
```
Mar 21 10:19:33 192.168.1.7 python3[4691]: detected unhandled Python exception in '/usr/bin/terminator'
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]: Traceback (most recent call last):
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]:   File "/usr/lib/python3.13/site-packages/terminatorlib/terminal_popup_menu.py", line 198, in <lambda>
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]:     self.terminal.get_cwd()))
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]:     ~~~~~~~~~~~~~~~~~~~~~^^
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]:   File "/usr/lib/python3.13/site-packages/terminatorlib/terminal.py", line 260, in get_cwd
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]:     return(GLib.filename_from_uri(vte_cwd)[0])
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]:            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
Mar 21 10:19:33 192.168.1.7 terminator.desktop[4691]: gi.repository.GLib.GError: g_convert_error: The hostname of the URI “file://192.168.1.7/home/shurdanil” is invalid (4)
```

**Comment by rgdoliveira** [comment]
This issue started happening on my machine this week. I'm using Fedora 42 and GNOME Shell version 48.2

**Comment by mattrose** [comment]
f42 package is in testing https://bodhi.fedoraproject.org/updates/FEDORA-2025-26cbe5be41

I'm gonna close this bug as it's fixed and pushed everywhere I can push to
