### ISSUE TITLE
Logger plugin not working with Linux Mint 22. Terminal becomes almost non-responsive.

### ISSUE THREAD

**Issue by mnmitch** [gnome-terminator/terminator#963]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**
Logger plugin has stopped working with Linux Mint 22. Plugin launches normally and allows the user to select the file name and target directory as normal. The first command issued on the terminal responds normally as well. After that, the terminal response becomes extremely sluggish and almost non-responsive. Ending the Logger plugin does not resolve the issue. You have to close the Terminator window and relaunch it to clear things up. 

The file from the Logger plugin is present in the target directory but there are zero contents present inside the file when opened.

Issue has been seen on three individual Linux Mint 22 boxes (all updates are current). Issue is not seen with Linux Mint 21 (also with all updates current)

**To Reproduce**
Launch Terminator
Start Logger 
	right click -> start logger
	Select target directory and file name
Issue "ls -al"
Issue "ls -al" <- Terminator becomes almost non-responsive here.

**Expected behavior**
The behavior with Linux Mint 21 is that the terminal remains responsive and all data presented on the console is captured and saved to the target file.

**Screenshots**
No screenshots of laggy behavior or empty file.

**Desktop (please complete the following information):**
************
WORKSTATION
***********
OS: Linux Mint 22 x86_64 
Host: SH67H3 1.0 
Kernel: 6.8.0-49-generic 
Uptime: 1 day, 10 hours, 49 mins 
Packages: 2483 (dpkg) 
Shell: bash 5.2.21 
Resolution: 1600x1200 
DE: Cinnamon 6.2.9 
WM: Mutter (Muffin) 
WM Theme: CBlack (Mint-Y) 
Theme: Mint-Y-Blue [GTK2/3] 
Icons: buuf3.34 [GTK2/3] 
Terminal: terminator 
CPU: Intel i7-2600 (8) @ 3.800GHz 
GPU: Intel 2nd Generation Core Processor Family 
Memory: 2357MiB / 15902MiB 

*********************
TERMINATOR
*********************
Version 2.1.3

**Additional context**
**********************
CONFIG FILE
**********************
extreme@shuttleHome:~/.config/terminator$ cat config
[global_config]
  enabled_plugins = Logger, LaunchpadBugURLHandler, LaunchpadCodeURLHandler, APTURLHandler
[keybindings]
[profiles]
  [[default]]
    scrollback_infinite = True
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      size = 900, 1100
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = default
[plugins]

**Comment by mnmitch** [comment]
Probably should have included that using the Linux commands "script output.txt" to log console contents and "Ctrl-D" to end the capture work as expected.

**Comment by mnmitch** [comment]
Behavior is still present with Mint 22.1 release. Behavior is not present on Mint 21.1.

**Comment by mattrose** [comment]
Hmm, I can't reproduce this at all using the steps you provided.  Can you try running terminator in debug mode to see if there's something that is causing this?  `terminator -d`

**Comment by pwhitaker** [comment]
Was this resolved? I have the same issue, Mint 22.
In debug mode, logger enabled:

(terminator:133677): VTE-WARNING **: 20:15:03.232: vte_terminal_get_text_range: Passing a GArray to retrieve attributes is deprecated. In a future version, passing non-NULL as attributes array will make the function return NULL.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/terminatorlib/plugins/logger.py", line 61, in save
    self.write_content(terminal, last_saved_row, last_saved_col, row, col)
  File "/usr/lib/python3/dist-packages/terminatorlib/plugins/logger.py", line 48, in write_content
    fd.write(content[:-1])
             ~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/terminatorlib/plugins/logger.py", line 61, in save
    self.write_content(terminal, last_saved_row, last_saved_col, row, col)
  File "/usr/lib/python3/dist-packages/terminatorlib/plugins/logger.py", line 48, in write_content
    fd.write(content[:-1])
             ~~~~~~~^^^^^
